# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chatbot.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'chatbot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rchatbot.proto\x12\x07\x63hatbot\"\x1e\n\x0bUserMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"/\n\x0b\x42otResponse\x12\x0e\n\x06intent\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\t2E\n\x0e\x43hatbotService\x12\x33\n\x05Query\x12\x14.chatbot.UserMessage\x1a\x14.chatbot.BotResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatbot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERMESSAGE']._serialized_start=26
  _globals['_USERMESSAGE']._serialized_end=56
  _globals['_BOTRESPONSE']._serialized_start=58
  _globals['_BOTRESPONSE']._serialized_end=105
  _globals['_CHATBOTSERVICE']._serialized_start=107
  _globals['_CHATBOTSERVICE']._serialized_end=176
# @@protoc_insertion_point(module_scope)
